arr.push_back(1);
    arr.push_back(2);
    arr.push_back(3);
    arr.push_back(3);
    arr.push_back(5);
    arr.push_back(8);
    arr.push_back(10);
    arr.push_back(10);
    arr.push_back(11);
    int n = arr.size();